version: "2"
services:
 router:
  environment:
   - ref_service_host=ref-service
   - ref_service_port=9010
  image: dispatch/router:0.1.0-SNAPSHOT
  ports:
   - "9010:8080"

 ref-service:
  image: dispatch/ref_service:0.1.0-SNAPSHOT
  environment:
   - db_jdbc_url=jdbc:postgresql://db:5432/example
   - db_user=example
   - db_password=example

 dispatch-service:
   environment:
    - ref_service_host=ref-service
    - ref_service_port=9010
    - sms_gateway_send_msg_url=http://sms-gateway:8080/api/sendMsg
    - sms_gateway_read_timeout=20000
   image:  dispatch/dispatch_service:0.1.0-SNAPSHOT

 db:
   image: postgres:10.4
   restart: always
   environment:
     POSTGRES_USER: example
     POSTGRES_PASSWORD: example
   volumes:
     - "./pgdata:/var/lib/postgresql/data"
   ports:
     - "5432:5432"
   logging:
       driver: none

 sms-gateway:
  environment:
   - sms_sender_max_random=10
   - sms_sender_fail_when_less=3
   - sms_sender_wait_seconds=10
  image: dispatch/sms_gateway:0.1.0-SNAPSHOT
  ports:
   - "9011:8080"

 pgadmin:
  image: dpage/pgadmin4
  ports:
    - 80
  environment:
    - PGADMIN_DEFAULT_PASSWORD=example
    - PGADMIN_DEFAULT_EMAIL=example
  logging:
      driver: none

volumes:
  pgdata:
